name: Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pipenv'
    - name: Install pipenv
      run: pipx install pipenv
    - name: Install dependencies
      run: |
        pipenv sync
        pipenv sync --categories build
    - name: Build with Nuitka
      run: pipenv run build-windows
    - name: Upload the build artifact
      uses: actions/upload-artifact@v4
      with:
        name: SimpleTranslator
        path: ${{ github.workspace }}\dist\SimpleTranslator.exe
        if-no-files-found: error
        retention-days: 1

  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pipenv'
    - name: Install pipenv
      run: pipx install pipenv
    - name: Install dependencies
      run: pipenv sync --dev
    - name: Lint with Ruff
      run: pipenv run ruff check --output-format=github
    - name: Type check with mypy
      run: pipenv run mypy .
