name: Release

on:
  push:
    tags: ['v*']

jobs:
  release:
    name: Release

    runs-on: windows-latest

    steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pipenv'
    - name: Install pipenv
      run: pipx install pipenv
    - name: Install dependencies
      run: |
        pipenv sync
        pipenv sync --categories build
    - name: Build with Nuitka
      run: pipenv run build-windows
    - name: Create a release
      run: |
        gh release create ${{ github.ref_name }} --generate-notes
        gh release upload ${{ github.ref_name }} dist\SimpleTranslator.exe
